spring.application.name=taskmanager
spring.datasource.url=jdbc:postgresql://localhost:5333/postgres
spring.datasource.username=Chandana
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
