spring.application.name=taskmanager
spring.datasource.url=jdbc:postgresql://localhost:5333/postgres
spring.datasource.username=Chandana
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG
jwt.secret=404E635266546A576E5A7234753778214125442A472D4B6150645367566B59
jwt.expiration=86400000
